# Generated by Django 6.0.2 on 2026-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_botmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
