# Generated by Django 5.2 on 2026-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_botmessage_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], default='backend', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_link',
            field=models.URLField(blank=True, default='', help_text='YouTube video havolasi'),
        ),
    ]
